patches-version = "dev"
cli-version = "dev"
enable-module-update = true

[twitter-piko]
enabled = true
pkg-name = "com.twitter.android"
app-name = "twitter"
rv-brand = "morphe-piko"
build-mode = "apk"
arch = "auto"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
dpi = "auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.twitter.android"
