patches-version = "dev"
cli-version = "dev"
enable-module-update = true

[twitter-piko]
enabled = false
pkg-name = "com.twitter.android"
app-name = "twitter"
rv-brand = "morphe-piko"
build-mode = "apk"
arch = "auto"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
dpi = "auto"

[instagram-piko]
enabled = true
pkg-name = "com.instagram.android"
app-name = "instagram"
rv-brand = "morphe-piko"
build-mode = "apk"
arch = "auto"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
dpi = "auto"
