#!/bin/bash
set -euo pipefail

cd build || { echo "build folder not found"; exit 1; }

: "${TG_TOKEN:?TG_TOKEN is not set}"
: "${TG_CHAT_ID:?TG_CHAT_ID is not set}"
: "${NEXT_VER_CODE:?NEXT_VER_CODE is not set}"
: "${GITHUB_SERVER_URL:?GITHUB_SERVER_URL is not set}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is not set}"

BUILD_LOG="../build.tmp"
BUILD_JSON="../build.json"

# Convert the APK filename to the base application slug.
get_app_slug() {
  local filename="$1"
  local base="${filename%.apk}"
  local prefix="${base%%-v*}"
  prefix="${prefix%-morphe-piko}"
  prefix="${prefix%-morphe}"
  prefix="${prefix%-piko}"
  echo "$prefix"
}

# Friendly application name, without the patch/brand suffix.
get_app_name() {
  local slug="$1"
  case "$slug" in
    youtube-music) echo "YouTube Music" ;;
    youtube)       echo "YouTube" ;;
    instagram)     echo "Instagram" ;;
    twitter)       echo "Twitter" ;;
    tiktok)        echo "TikTok" ;;
    reddit)        echo "Reddit" ;;
    spotify)       echo "Spotify" ;;
    *)             echo "$slug" | sed 's/-/ /g' ;;
  esac
}

get_app_version() {
  local filename="$1"
  local base="${filename%.apk}"
  local after_v="${base#*-v}"
  after_v="${after_v%-all}"
  after_v="${after_v%-arm64-v8a}"
  after_v="${after_v%-universal}"
  echo "$after_v"
}

# Return "friendly-repo version" for the patches actually used by this app.
# build.json contains the per-app patches reference generated by build.sh.
get_patches_info() {
  local slug="$1"
  local version="$2"
  local patches=""

  if [ -f "$BUILD_JSON" ]; then
    patches="$(jq -r --arg slug "$slug" --arg ver "$version" '
      to_entries[]
      | select(.value.version == $ver)
      | select((.value.name // "" | ascii_downcase | startswith($slug | ascii_downcase)))
      | .value.patches // empty
    ' "$BUILD_JSON" 2>/dev/null | head -n1 || true)"
  fi

  if [ -z "$patches" ]; then
    # Safe fallback from the APK naming convention.
    local base
    base="${slug}"
    case "$1" in
      instagram|twitter|tiktok|reddit) patches="crimera/piko" ;;
      youtube|youtube-music)            patches="MorpheApp/morphe-patches" ;;
      *)                                patches="" ;;
    esac
  fi

  local out=()
  local item repo display ver
  # patches may contain one or more source/file references separated by spaces.
  for item in $patches; do
    repo="${item%%/*}"
    if [[ "$item" == */* ]]; then
      # Keep owner/repo when present.
      repo="${item%/*}"
      # The source repo is the part before the patch artifact filename.
      repo="${repo%/*}"
    fi

    case "${item,,}" in
      *crimera/piko*|*crimera/piko/*) display="piko" ;;
      *morpheapp/morphe-patches*|*morpheapp/morphe-patches/*) display="morphe-patches" ;;
      *)
        display="${repo##*/}"
        display="${display%.git}"
        ;;
    esac

    # Extract the patch version from the artifact name.
    ver="$(printf '%s\n' "$item" | grep -oE 'patches-[vV]?[0-9][0-9A-Za-z._-]*|-[vV]?[0-9][0-9A-Za-z._-]*\.(mpp|jar|rvp|apk)' | head -n1 || true)"
    ver="$(printf '%s\n' "$ver" | sed -E 's/^patches-[vV]?//; s/^-([vV])?//; s/\.(mpp|jar|rvp|apk)$//')"

    if [ -n "$display" ]; then
      if [ -n "$ver" ]; then
        out+=("${display} ${ver}")
      else
        out+=("${display}")
      fi
    fi
  done

  if [ "${#out[@]}" -gt 0 ]; then
    local IFS=' + '
    echo "${out[*]}"
  else
    echo "unknown"
  fi
}

# Find the actual Morphe Desktop jar used/available in the build workspace.
get_morphe_desktop_version() {
  local jar name ver

  jar="$(find .. -type f -name 'morphe-desktop-*.jar' 2>/dev/null | head -n1 || true)"
  if [ -n "$jar" ]; then
    name="${jar##*/}"
    ver="${name#morphe-desktop-}"
    ver="${ver%-all.jar}"
    ver="${ver%.jar}"
    echo "$ver"
    return
  fi

  # Fallback to the build summary if the jar is no longer present.
  if [ -f "$BUILD_LOG" ]; then
    ver="$(grep -Eo 'morphe-desktop-[0-9A-Za-z._-]+(-all)?\.jar' "$BUILD_LOG" 2>/dev/null | head -n1 | sed -E 's/^morphe-desktop-//; s/-all\.jar$//; s/\.jar$//' || true)"
    if [ -n "$ver" ]; then
      echo "$ver"
      return
    fi
  fi

  echo "unknown"
}

MORPHE_DESKTOP_VERSION="$(get_morphe_desktop_version)"

for APK in *.apk; do
  [ -f "$APK" ] || continue

  APP_SLUG="$(get_app_slug "$APK")"
  APP_NAME="$(get_app_name "$APP_SLUG")"
  APP_VERSION="$(get_app_version "$APK")"
  PATCHES_INFO="$(get_patches_info "$APP_SLUG" "$APP_VERSION")"

  DOWNLOAD_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${NEXT_VER_CODE}/${APK}"

  MESSAGE="🎉 New Build Available

${APP_NAME} ${APP_VERSION}
Patches: ${PATCHES_INFO}
Morphe Desktop: ${MORPHE_DESKTOP_VERSION}

📥 Download:

${DOWNLOAD_URL}"

  curl --fail --silent --show-error --request POST \
    --data-urlencode "chat_id=${TG_CHAT_ID}" \
    --data-urlencode "text=${MESSAGE}" \
    --data-urlencode "disable_web_page_preview=true" \
    "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" >/dev/null

  echo "Telegram notification sent for: ${APK}"
done
