[youtube-morphe]
enabled = true
pkg-name = "com.google.android.youtube"
app-name = "youtube"
patch-folder = "youtube"
rv-brand = "morphe"
build-mode = "both"
arch = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "auto"

[youtube-music-morphe]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "youtube-music"
patch-folder = "music"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.apps.youtube.music"


[youtube-music-morphe-exp]
enabled = true
pkg-name = "com.google.android.apps.youtube.music"
app-name = "youtube-music"
patch-folder = "music"
rv-brand = "morphe-exp"
build-mode = "both"
version = "exp"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.apps.youtube.music"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
apkcombo-dlurl = "https://apkcombo.com/youtube-music/com.google.android.apps.youtube.music"

[reddit-morphe-exp]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "reddit"
rv-brand = "morphe-exp"
build-mode = "both"
arch = "both"
version = "exp"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.reddit.frontpage"

[reddit-morphe]
enabled = true
pkg-name = "com.reddit.frontpage"
app-name = "reddit"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.reddit.frontpage"
