[twitter-morphe]
enabled = true 
pkg-name = "com.twitter.android"
app-name = "twitter"
rv-brand = "morphe"
build-mode = "both"
arch = "auto"
patches-source = "crimera/piko"
# patches-source = "'inotia00/x-shim' 'crimera/piko'"
# patches-source-host = "'gitlab' 'github'"
# version = "11.81.0-release.0"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
dpi = "auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.twitter.android"

[twitter-morphe-materialu]
enabled = true
pkg-name = "com.twitter.android"
app-name = "twitter"
rv-brand = "morphe-materialu"
build-mode = "both"
arch = "auto"
patches-source = "crimera/piko"
# patches-source-host = "'gitlab' 'github'"
# patcher-args = "--continue-on-error"
included-patches = "'Bring back twitter' 'Dynamic color'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
dpi = "auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
apkpure-dlurl = "https://apkpure.com/x-formerly-twitter/com.twitter.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.twitter.android"

[instagram-morphe-piko]
enabled = true
pkg-name = "com.instagram.android"
app-name = "instagram"
rv-brand = "morphe-piko"
build-mode = "both"
arch = "auto"
patches-source = "crimera/piko"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
dpi = "auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.instagram.android"
